[package]
name = "files"
version = "0.1.0"
authors = ["bloatoo <bloatoo@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.14.0"
termion = "1.5.6"
